using System.Globalization;
using System.Text;

namespace Workes.SaveSystem.SerializerComparison.Tests;

public sealed class SerializerSizeComparisonTests
{
    [Test]
    public void GenerateSerializerSizeComparisonExamples()
    {
        var outputRoot = Path.Combine(SerializerComparisonFixtures.GetRepositoryRoot(), "tests", "obj", "SerializerSizeComparison");
        if (Directory.Exists(outputRoot))
            Directory.Delete(outputRoot, recursive: true);
        Directory.CreateDirectory(outputRoot);

        var scenarios = SerializerComparisonFixtures.CreateScenarios();
        var serializerCases = SerializerComparisonFixtures.CreateSerializerCases();

        var results = new List<SizeResult>();
        foreach (var scenario in scenarios)
        {
            foreach (var serializerCase in serializerCases)
            {
                var saveRoot = Path.Combine(outputRoot, scenario.Id, serializerCase.Id);
                results.Add(WriteAndMeasure(scenario, serializerCase, saveRoot));
            }
        }

        WriteSummary(outputRoot, scenarios, serializerCases, results);

        Assert.That(File.Exists(Path.Combine(outputRoot, "README.md")), Is.True);
        Assert.That(File.Exists(Path.Combine(outputRoot, "summary.csv")), Is.True);
        foreach (var scenario in scenarios)
        {
            var scenarioResults = results.Where(result => result.ScenarioId == scenario.Id).ToArray();
            Assert.That(scenarioResults.Select(result => result.SerializerId), Is.EquivalentTo(serializerCases.Select(serializer => serializer.Id)));
            Assert.That(scenarioResults.All(result => result.ProviderBytes > 0), Is.True);
            Assert.That(scenarioResults.All(result => result.MetadataBytes > 0), Is.True);
            Assert.That(scenarioResults.All(result => result.TotalBytes > 0), Is.True);
        }
    }

    private static SizeResult WriteAndMeasure(ComparisonScenario scenario, SerializerCase serializerCase, string saveRoot)
    {
        var serializer = serializerCase.CreateSerializer();
        var provider = new ComparisonProvider(SerializerComparisonFixtures.CloneState(scenario.State));
        var manager = SerializerComparisonFixtures.CreateManager(saveRoot, serializer);

        manager.RegisterProvider(provider);
        manager.ValidateRegistrations();
        manager.SaveToDisk(SerializerComparisonFixtures.SaveIdentity);

        var saveFolder = Path.Combine(saveRoot, SerializerComparisonFixtures.SaveIdentity);
        var providerPath = Path.Combine(saveFolder, SerializerComparisonFixtures.ProviderSaveKey + serializer.FileExtension);
        var metadataPath = Path.Combine(saveFolder, "metadata" + serializer.FileExtension);

        Assert.That(File.Exists(providerPath), Is.True);
        Assert.That(File.Exists(metadataPath), Is.True);

        return new SizeResult(
            scenario.Id,
            serializerCase.Id,
            serializerCase.DisplayName,
            new FileInfo(providerPath).Length,
            new FileInfo(metadataPath).Length,
            Directory.EnumerateFiles(saveFolder, "*", SearchOption.AllDirectories).Sum(path => new FileInfo(path).Length));
    }

    private static void WriteSummary(
        string outputRoot,
        IReadOnlyList<ComparisonScenario> scenarios,
        IReadOnlyList<SerializerCase> serializerCases,
        IReadOnlyList<SizeResult> results)
    {
        var readme = new StringBuilder();
        readme.AppendLine("# Serializer Size Comparison");
        readme.AppendLine();
        readme.AppendLine("Generated by `Workes.SaveSystem.SerializerComparison.Tests`. Byte counts include provider payloads, save metadata, and total save-folder size. Percentages use compact JSON as the baseline for each scenario.");
        readme.AppendLine();

        var csv = new StringBuilder();
        csv.AppendLine("scenario,serializer,provider_bytes,metadata_bytes,total_bytes,total_percent_of_compact_json");

        foreach (var scenario in scenarios)
        {
            readme.AppendLine("## " + scenario.Id);
            readme.AppendLine();
            readme.AppendLine("| Serializer | Provider bytes | Metadata bytes | Total bytes | Total vs compact JSON |");
            readme.AppendLine("|---|---:|---:|---:|---:|");

            var scenarioResults = serializerCases
                .Select(serializer => results.Single(result => result.ScenarioId == scenario.Id && result.SerializerId == serializer.Id))
                .ToArray();
            var compactTotal = scenarioResults.Single(result => result.SerializerId == "compact-json").TotalBytes;

            foreach (var result in scenarioResults)
            {
                var percent = compactTotal == 0 ? 0 : (double)result.TotalBytes / compactTotal * 100;
                readme.AppendLine(
                    string.Format(
                        CultureInfo.InvariantCulture,
                        "| {0} | {1:N0} | {2:N0} | {3:N0} | {4:0.0}% |",
                        result.SerializerDisplayName,
                        result.ProviderBytes,
                        result.MetadataBytes,
                        result.TotalBytes,
                        percent));
                csv.AppendLine(
                    string.Format(
                        CultureInfo.InvariantCulture,
                        "{0},{1},{2},{3},{4},{5:0.0}",
                        scenario.Id,
                        result.SerializerId,
                        result.ProviderBytes,
                        result.MetadataBytes,
                        result.TotalBytes,
                        percent));
            }

            readme.AppendLine();
        }

        File.WriteAllText(Path.Combine(outputRoot, "README.md"), readme.ToString());
        File.WriteAllText(Path.Combine(outputRoot, "summary.csv"), csv.ToString());
    }

    private sealed record SizeResult(
        string ScenarioId,
        string SerializerId,
        string SerializerDisplayName,
        long ProviderBytes,
        long MetadataBytes,
        long TotalBytes);
}
