using System;
using System.IO;
using Workes.SaveSystem;

namespace Workes.SaveSystem.Tests;

public sealed class SerializerOutputExampleTests
{
    [Test]
    public void WriteSerializerOutputExamples()
    {
        var outputRoot = GetOutputRoot();
        if (Directory.Exists(outputRoot))
            Directory.Delete(outputRoot, recursive: true);
        Directory.CreateDirectory(outputRoot);

        WriteExampleSave(new JsonSaveSerializer(), Path.Combine(outputRoot, "json"));
        WriteExampleSave(new BinarySaveSerializer(), Path.Combine(outputRoot, "binary"));
        File.WriteAllText(
            Path.Combine(outputRoot, "README.txt"),
            "These examples are generated by SerializerOutputExampleTests.\r\n" +
            "json/example-slot/player.json is readable JSON text.\r\n" +
            "binary/example-slot/player.bin is Base64 text containing Workes.SaveSystem's binary token payload.\r\n" +
            "The .bin file is not raw binary bytes because ISaveSerializer currently persists provider payloads as strings.\r\n");

        var jsonPayload = File.ReadAllText(Path.Combine(outputRoot, "json", "example-slot", "player.json"));
        var binaryPayload = File.ReadAllText(Path.Combine(outputRoot, "binary", "example-slot", "player.bin"));

        Assert.That(jsonPayload.TrimStart(), Does.StartWith("{"));
        Assert.DoesNotThrow(() => Convert.FromBase64String(binaryPayload));
        Assert.That(binaryPayload.TrimStart(), Does.Not.StartWith("{"));
    }

    private static void WriteExampleSave(ISaveSerializer serializer, string saveRoot)
    {
        var manager = new SaveManager<string>(
            SaveSystemOptions.Create(
                saveRootPath: saveRoot,
                serializer: serializer));
        manager.RegisterProvider(new PlayerProvider());
        manager.ValidateRegistrations();
        manager.SaveToDisk("example-slot");
    }

    private static string GetOutputRoot()
    {
        var testProjectRoot = Path.GetFullPath(Path.Combine(TestContext.CurrentContext.TestDirectory, "..", "..", ".."));
        return Path.Combine(testProjectRoot, "obj", "SerializerOutputExamples");
    }

    public sealed class PlayerState
    {
        public string Name { get; set; } = "Rook";

        public int Level { get; set; } = 4;

        public bool HasKey { get; set; } = true;
    }

    private sealed class PlayerProvider : ISaveProvider<PlayerState>
    {
        public string SaveKey => "player";

        public int SchemaVersion => 1;

        public int LoadPriority => 0;

        public PlayerState CaptureState()
        {
            return new PlayerState();
        }

        public void RestoreState(PlayerState state)
        {
        }
    }
}
