using System;
using System.IO;
using System.IO.Compression;
using System.Text;
using Workes.SaveSystem;

namespace Workes.SaveSystem.Tests;

public sealed class SerializerOutputExampleTests
{
    [Test]
    public void WriteSerializerOutputExamples()
    {
        var outputRoot = GetOutputRoot();
        if (Directory.Exists(outputRoot))
            Directory.Delete(outputRoot, recursive: true);
        Directory.CreateDirectory(outputRoot);

        WriteExampleSave(new JsonSaveSerializer(), Path.Combine(outputRoot, "json-pretty"));
        WriteExampleSave(new JsonSaveSerializer(JsonSaveFormatting.Compact), Path.Combine(outputRoot, "json-compact"));
        WriteExampleSave(
            new CompressedSaveSerializer(new JsonSaveSerializer(JsonSaveFormatting.Compact)),
            Path.Combine(outputRoot, "json-compact-gzip"));
        File.WriteAllText(
            Path.Combine(outputRoot, "README.txt"),
            "These examples are generated by SerializerOutputExampleTests.\r\n" +
            "json-pretty/example-slot/player.json is indented JSON text.\r\n" +
            "json-pretty/example-slot/metadata.json is metadata serialized through JsonSaveSerializer.\r\n" +
            "json-compact/example-slot/player.json is compact JSON text.\r\n" +
            "json-compact/example-slot/metadata.json is metadata serialized through JsonSaveSerializer.\r\n" +
            "json-compact-gzip/example-slot/player.json.gz is compact JSON compressed with GZip.\r\n" +
            "json-compact-gzip/example-slot/metadata.json.gz is metadata serialized through JsonSaveSerializer and compressed with GZip.\r\n");

        var prettyPayload = File.ReadAllText(Path.Combine(outputRoot, "json-pretty", "example-slot", "player.json"));
        var compactPayload = File.ReadAllText(Path.Combine(outputRoot, "json-compact", "example-slot", "player.json"));
        var compressedPayload = DecompressToText(Path.Combine(outputRoot, "json-compact-gzip", "example-slot", "player.json.gz"));

        Assert.That(prettyPayload.TrimStart(), Does.StartWith("{"));
        Assert.That(prettyPayload, Does.Contain(Environment.NewLine));
        Assert.That(compactPayload.TrimStart(), Does.StartWith("{"));
        Assert.That(compactPayload, Does.Not.Contain(Environment.NewLine));
        Assert.That(compressedPayload.TrimStart(), Does.StartWith("{"));
        Assert.That(compressedPayload, Does.Not.Contain(Environment.NewLine));
        Assert.That(File.Exists(Path.Combine(outputRoot, "json-pretty", "example-slot", "metadata.json")), Is.True);
        Assert.That(File.Exists(Path.Combine(outputRoot, "json-compact", "example-slot", "metadata.json")), Is.True);
        Assert.That(File.Exists(Path.Combine(outputRoot, "json-compact-gzip", "example-slot", "metadata.json.gz")), Is.True);
    }

    private static void WriteExampleSave(ISaveSerializer serializer, string saveRoot)
    {
        var manager = new SaveManager<string>(
            SaveSystemOptions.Create(
                saveRootPath: saveRoot,
                serializer: serializer));
        manager.RegisterProvider(new PlayerProvider());
        manager.ValidateRegistrations();
        manager.SaveToDisk("example-slot");
    }

    private static string GetOutputRoot()
    {
        var testProjectRoot = Path.GetFullPath(Path.Combine(TestContext.CurrentContext.TestDirectory, "..", "..", ".."));
        return Path.Combine(testProjectRoot, "obj", "SerializerOutputExamples");
    }

    private static string DecompressToText(string path)
    {
        using var input = File.OpenRead(path);
        using var gzip = new GZipStream(input, CompressionMode.Decompress);
        using var output = new MemoryStream();
        gzip.CopyTo(output);
        return Encoding.UTF8.GetString(output.ToArray());
    }

    public sealed class PlayerState
    {
        public string Name { get; set; } = "Rook";

        public int Level { get; set; } = 4;

        public bool HasKey { get; set; } = true;
    }

    private sealed class PlayerProvider : ISaveProvider<PlayerState>
    {
        public string SaveKey => "player";

        public int SchemaVersion => 1;

        public int LoadPriority => 0;

        public PlayerState CaptureState()
        {
            return new PlayerState();
        }

        public void RestoreState(PlayerState state)
        {
        }
    }
}
